### ISSUE TITLE
How to set option being selected?

### ISSUE THREAD

**Issue by wukongrita** [ember-bootstrap/ember-bootstrap-power-select#311] opened 2022-05-16 05:38 UTC
Hi All and @simonihmig,

I wonder how to set the selected option that been selected by user?
Although the object of the model changed, but the selected option isn't selected and the highlight (blue color) being selected at the first option.

Here is when the data already loaded, the option being selected (grey color):
![image](https://user-images.githubusercontent.com/25361005/168524533-0e42fc35-1872-40c2-ae02-e483c3565d01.png)

But; when user changing the option (to other options; Spanish in this case), there is no selected (grey color) (even the object is changing):
![image](https://user-images.githubusercontent.com/25361005/168524798-275a9f29-c221-43ca-ad9e-0ed832f1bd18.png)

Here are my models:
// core-user.js
```
. . .
export default class CoreUserModel extends Model.extend(Validations) {
  @attr name;

  @belongsTo coreLocale;
}
```

// core-locale.js
```
. . .
export default class CoreLocaleModel extends Model.extend(Validations) {
  @attr tag;
  @attr name;

  @hasMany coreUsers;
}
```

My Component:
// user-profile.hbs
```
<BsForm @model={{@model}} as |form|>
  ...
  <form.element
    @controlType="power-select"
    @label="Language"
    @options={{this.locales}}
    @property="coreLocale"
    @optionLabelPath="name"
  />
  ...
</BsForm>
```

// user-profile.js
```
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class UserProfileIndexComponent extends Component {
  @service store;

  @tracked locales;

  constructor() {
    super(...arguments);

    this.locales = this.store.query('core-locale', {
      sort: 'name'
    });
  }
}
```

The JSON API Response:
// core-users
```
{
  "data": {
    "type": "core-users",
    "id": "1204f808-9128-4c4f-8784-7a119592e9de",
    "attributes": {
      "name": "Rizky Tahara Shita",
    },
    "relationships": {
      "core-locale": {
        "data": {
          "type": "coreLocale",
          "id": "en"
        }
      }
    }
  },
  "included": [
    {
      "type": "coreLocale",
      "id": "en",
      "attributes": {
        "tag": "en-US",
        "name": "English"
      }
    }
  ]
}
```

// core-locale
```
{
  "data": [
    {
      "type": "core-locales",
      "id": "id",
      "attributes": {
        "tag": "id-ID",
        "name": "Bahasa Indonesia"
      }
    },
    {
      "type": "core-locales",
      "id": "en",
      "attributes": {
        "tag": "en-US",
        "name": "English"
      }
    },
    {
      "type": "core-locales",
      "id": "de",
      "attributes": {
        "tag": "de-DE",
        "name": "Germany"
      }
    },
    {
      "type": "core-locales",
      "id": "es",
      "attributes": {
        "tag": "es-ES",
        "name": "Spanish"
      }
    }
  ],
  "meta": {
    "pagination": {
      "total": 4,
      "count": 4,
      "per_page": 15,
      "current_page": 1,
      "total_pages": 1
    }
  },
  "links": {
    "self": "http://api.local/core-locales?sort=name&page=1",
    "first": "http://api.local/core-locales?sort=name&page=1",
    "last": "http://api.local/core-locales?sort=name&page=1"
  }
}
```

Did I missed someting?

Environment:
Ember: 3.20
Ember Bootstrap Power Select: 3.0.1

**Comment by simonihmig** [comment] 2022-05-30 11:59
First, sorry for the late answer. I don't see an obvious mistake. 

I was not exactly sure though what the problem is: when the user selects a different option, is the change not applied, or does `@model.coreLocale` change, and only the power-select's rendering is not correct?

**Comment by wukongrita** [comment] 2022-05-31 19:09
Yes, the model correctly changed; but the rendering is not being selected by the grey color

**Comment by jelhan** [comment] 2022-07-19 10:11
@wukongrita Did you fixed the issue in the meantime? If not, do you mind creating a reproduction? That would be very helpful to debug.

**Comment by jelhan** [comment] 2023-02-18 22:16
I quickly checked in dummy app. It is working as expected there. Going to close this issue due to missing reproduction. Please provide a reproduction if you still struggle with it.

**Closed by jelhan** 2023-02-18 22:16 UTC
